---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 34197, host: 34197, auto_correct: true, protocol: udp}]
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[factorio::default]
    attributes:
