---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6-5-x64
  driver:
    name: digitalocean

- name: centos-7-0-x64
  driver:
    name: digitalocean

- name: debian-7-0-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[factorio::default]