source 'https://rubygems.org'

gem 'chefspec'
gem 'test-kitchen'
gem 'kitchen-pester'
gem 'kitchen-vagrant'
gem 'vagrant-wrapper', '>= 2.0'
gem 'winrm-transport'
gem 'berkshelf'
gem 'stove'
gem 'rubocop'
gem 'rake'
gem 'foodcritic'
gem 'kitchen-digitalocean'
